"""Provenance pin for the DCD_f / MEG critical values (§5).

Guards that the critical-value constants in art.formal_tests stay equal to the versioned
Monte-Carlo table research/sf_meg/crit_table.json (generated by dcd_mc.py + final_table.py,
seed=0, 20000 reps/freq). If a constant is edited without regenerating — or the MC is rerun
and the committed table not updated — this fails, so the hardcoded values can never silently
drift from their documented, reproducible source. See research/sf_meg/README.md.
"""
import json
import os

import pytest

from art.formal_tests import (
    _DCD_CRIT_MA_F_TABLE,
    _DCD_CRIT_MA,
    _DCD_CRIT_MA_F_ASYMP,
)

_JSON = os.path.join(os.path.dirname(__file__), "..", "research", "sf_meg", "crit_table.json")


def _load():
    if not os.path.exists(_JSON):
        pytest.skip(f"provenance table not found: {_JSON}")
    with open(_JSON) as fh:
        return json.load(fh)


def test_complex_table_matches_provenance():
    j = _load()
    cbn = {int(k): tuple(v) for k, v in j["complex_by_n"].items()}
    assert cbn == _DCD_CRIT_MA_F_TABLE


def test_real_root_matches_provenance():
    j = _load()
    assert tuple(j["real_root"]) == (
        _DCD_CRIT_MA["10%"], _DCD_CRIT_MA["5%"], _DCD_CRIT_MA["1%"])


def test_asymptotic_matches_provenance():
    j = _load()
    assert tuple(j["asymptotic_complex"]) == _DCD_CRIT_MA_F_ASYMP
