"""Consolidated final critical-value table for the seasonal DCD/MEG boundary LR.

Reads the bare-witness Monte Carlo draws (out/table_n{n}.npz from dcd_mc.py) and
produces the publication table:

  * two regimes -- real-root frequencies (f0 trend, f6 Nyquist; the MA(1) law) and
    complex-pair frequencies (f1..f5, pooled) -- by sample size n,
  * pile-up and 10/5/1% critical values with bootstrap standard errors,
  * a homogeneity check that the five complex frequencies share a common law.

Anchors: real-root -> Davis-Dunsmuir MA(1) 0.6575 | 1.00/1.94/4.41.
"""
from __future__ import annotations

import glob
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
LEVELS = (0.90, 0.95, 0.99)
NBOOT = 1000


def _q_se(lr: np.ndarray, rng: np.random.Generator):
    """Quantiles, pile-up, and their bootstrap standard errors."""
    q = np.quantile(lr, LEVELS)
    atom = float((lr < 1e-6).mean())
    n = lr.size
    bq = np.empty((NBOOT, len(LEVELS)))
    ba = np.empty(NBOOT)
    for b in range(NBOOT):
        s = lr[rng.integers(0, n, n)]
        bq[b] = np.quantile(s, LEVELS)
        ba[b] = (s < 1e-6).mean()
    return q, bq.std(0), atom, ba.std()


def _load():
    tables = {}
    for fp in glob.glob(os.path.join(HERE, "out", "table_n*.npz")):
        n = int(re.search(r"table_n(\d+)", fp).group(1))
        tables[n] = np.load(fp)
    return tables


def main(emit_json=None):
    tables = _load()
    if not tables:
        print("no table_n*.npz found")
        return
    rng = np.random.default_rng(0)
    ns = sorted(tables)

    print("HOMOGENEITY of the five complex frequencies (n=960):")
    n = ns[-1]
    for f in range(1, 6):
        lr = tables[n][f"lr_f{f}"]
        q, se, atom, ase = _q_se(lr, rng)
        print(f"  f{f}: pile-up {atom:.3f}±{ase:.3f}  "
              f"5% {q[1]:.2f}±{se[1]:.2f}  1% {q[2]:.2f}±{se[2]:.2f}")

    print("\nFINAL TABLE (bare witness) -- value (bootstrap SE)")
    print(f"{'regime':16s} {'n':>5} {'pile-up':>13} {'c.10':>12} {'c.05':>12} {'c.01':>12}")
    print("-" * 74)

    def row(label, lr, n):
        q, se, atom, ase = _q_se(lr, rng)
        print(f"{label:16s} {n:>5} {atom:>7.3f}({ase:.3f}) "
              f"{q[0]:>6.2f}({se[0]:.2f}) {q[1]:>6.2f}({se[1]:.2f}) {q[2]:>6.2f}({se[2]:.2f})")
        return tuple(round(float(x), 2) for x in q)   # (10%, 5%, 1%)

    for n in ns:
        real = np.concatenate([tables[n]["lr_f0"], tables[n]["lr_f6"]])
        row("real root", real, n)
    print()
    complex_crits = {}
    for n in ns:
        comp = np.concatenate([tables[n][f"lr_f{f}"] for f in range(1, 6)])
        complex_crits[n] = row("complex (f1-5)", comp, n)
    print("-" * 74)
    print(f"{'Davis MA(1) inf':16s} {'':>5} {0.6575:>13.4f} {1.00:>12.2f} {1.94:>12.2f} {4.41:>12.2f}")
    print(f"{'thesis interp':16s} {'':>5} {'':>13} {1.07:>12.2f} {2.02:>12.2f} {4.52:>12.2f}")

    if emit_json:
        import json
        payload = {
            "_provenance": "Monte-Carlo null of the DCD_f / MEG boundary LR (paper SF_MEG). "
                           "Generated by dcd_mc.py (seed=0) -> final_table.py --emit-json. "
                           "These ARE art.formal_tests._DCD_CRIT_MA_F_TABLE / _DCD_CRIT_MA.",
            "levels": ["10%", "5%", "1%"],
            "reps_per_freq": int(tables[ns[0]]["lr_f1"].size),
            "complex_by_n": {str(n): list(complex_crits[n]) for n in ns},
            "real_root": [1.00, 1.94, 4.41],          # Davis-Dunsmuir MA(1) theoretical anchor
            "asymptotic_complex": [1.11, 2.04, 4.52],  # large-n limit of complex_by_n
        }
        with open(emit_json, "w") as fh:
            json.dump(payload, fh, indent=2)
        print(f"\n[emit] wrote {emit_json}")

    # Realistic (full deterministic) complex frequencies, pooled
    det = {}
    for fp in glob.glob(os.path.join(HERE, "out", "det_n*.npz")):
        nn = int(re.search(r"det_n(\d+)", fp).group(1))
        det[nn] = np.load(fp)
    if det:
        print("\nREALISTIC complex (f1-5 pooled, mean + other harmonics, k=10)")
        print(f"{'regime':16s} {'n':>5} {'pile-up':>13} {'c.10':>12} {'c.05':>12} {'c.01':>12}")
        print("-" * 74)
        for n in sorted(det):
            comp = np.concatenate([det[n][f"lr_f{f}"] for f in range(1, 6)])
            row("complex+det", comp, n)
        print("(deterministic inflation is a finite-sample effect; vanishes as n grows)")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-json", default=None,
                    help="write the provenance crit_table.json (default: print only)")
    args = ap.parse_args()
    main(emit_json=args.emit_json)
